//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inzSNMWebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Ankieta = new HashSet<Ankieta>();
        }
    
        public int Id_admin { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public System.DateTime Data_reje { get; set; }
    
        public virtual ICollection<Ankieta> Ankieta { get; set; }
    }
}
