//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inzSNMWebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ankieta
    {
        public Ankieta()
        {
            this.Bierze_udzial = new HashSet<Bierze_udzial>();
            this.Dzieło = new HashSet<Dzieło>();
        }
    
        public int Id_ankiety { get; set; }
        public string Nazwa { get; set; }
        public string Opis_ankiety { get; set; }
        public System.DateTime Data_rozp { get; set; }
        public Nullable<System.DateTime> Data_zak { get; set; }
        public int Id_admin { get; set; }
        public Nullable<int> Id_Muzyka { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<Bierze_udzial> Bierze_udzial { get; set; }
        public virtual Muzyka Muzyka { get; set; }
        public virtual ICollection<Dzieło> Dzieło { get; set; }
    }
}
