//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inzSNMWebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bierze_udzial
    {
        public Bierze_udzial()
        {
            this.Ocena = new HashSet<Ocena>();
        }
    
        public int Id_Osoba { get; set; }
        public int Id_ankiety { get; set; }
    
        public virtual Ankieta Ankieta { get; set; }
        public virtual ICollection<Ocena> Ocena { get; set; }
        public virtual Glosujący Glosujący { get; set; }
    }
}
