//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inzSNMWebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocena
    {
        public int Ocena1 { get; set; }
        public int Id_Osoba { get; set; }
        public int Id_ankiety { get; set; }
        public int Id_zdjecia { get; set; }
    
        public virtual Bierze_udzial Bierze_udzial { get; set; }
        public virtual Dzieło Dzieło { get; set; }
    }
}
